version: '3.8'
services:
  app:
    build: .
    image: purchaseorder-app:latest 
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/Supermarket
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Supermarket
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./local_db_dump.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local